"""empty message

Revision ID: 17a36e27318f
Revises: None
Create Date: 2014-10-16 15:22:24.770513

"""

# revision identifiers, used by Alembic.
revision = '17a36e27318f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('academy_name', sa.String(length=255), nullable=True),
    sa.Column('teacher_name', sa.String(length=255), nullable=True),
    sa.Column('academy_introduce', sa.Text(), nullable=True),
    sa.Column('teacher_introduce', sa.Text(), nullable=True),
    sa.Column('curriculum_introduce', sa.Text(), nullable=True),
    sa.Column('academy_address', sa.String(length=255), nullable=True),
    sa.Column('academy_latlng', sa.String(length=255), nullable=True),
    sa.Column('welcome_line', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('class_time', sa.Text(), nullable=True),
    sa.Column('class_fee', sa.String(length=255), nullable=True),
    sa.Column('homepage', sa.String(length=255), nullable=True),
    sa.Column('image_1', sa.String(length=255), nullable=True),
    sa.Column('image_2', sa.String(length=255), nullable=True),
    sa.Column('image_3', sa.String(length=255), nullable=True),
    sa.Column('image_4', sa.String(length=255), nullable=True),
    sa.Column('image_5', sa.String(length=255), nullable=True),
    sa.Column('teacher_image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('academy')
    ### end Alembic commands ###
