"""empty message

Revision ID: 1f7fef618e20
Revises: 8ff7a960b90
Create Date: 2014-09-27 14:29:20.451000

"""

# revision identifiers, used by Alembic.
revision = '1f7fef618e20'
down_revision = '8ff7a960b90'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academy', sa.Column('image_1', sa.String(length=255), nullable=True))
    op.add_column('academy', sa.Column('image_2', sa.String(length=255), nullable=True))
    op.add_column('academy', sa.Column('image_3', sa.String(length=255), nullable=True))
    op.add_column('academy', sa.Column('image_4', sa.String(length=255), nullable=True))
    op.add_column('academy', sa.Column('image_5', sa.String(length=255), nullable=True))
    op.add_column('academy', sa.Column('teacher_image', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('academy', 'teacher_image')
    op.drop_column('academy', 'image_5')
    op.drop_column('academy', 'image_4')
    op.drop_column('academy', 'image_3')
    op.drop_column('academy', 'image_2')
    op.drop_column('academy', 'image_1')
    ### end Alembic commands ###
